name: PR Validation

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'Makefile'
      - '.github/workflows/pr-validation.yml'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.8.3
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.0'
        cache: 'poetry'

    - name: Install dependencies
      run: poetry install

    - name: Check code formatting
      run: make format

    - name: Run linting
      run: make lint

    - name: Run tests with coverage
      run: make test-cov
